service: CanooTakeHomeAPI-GETAPI

custom:
  secrets: ${file(secrets.json)}
  pythonRequirements:
    dockerizePip: non-linux

provider:
  name: aws
  runtime: python3.8
  region: us-east-2
  stage: dev
  environment:
    DBNAME: ${self:custom.secrets.DBNAME}
    USER: ${self:custom.secrets.USER}
    HOST: ${self:custom.secrets.HOST}
    PASS: ${self:custom.secrets.PASS}
    PORT: ${self:custom.secrets.PORT}

# you can add statements to the Lambda function's IAM Role here
#  iamRoleStatements:
#    - Effect: "Allow"
#      Action:
#        - "s3:ListBucket"
#      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
#    - Effect: "Allow"
#      Action:
#        - "s3:PutObject"
#      Resource:
#        Fn::Join:
#          - ""
#          - - "arn:aws:s3:::"
#            - "Ref" : "ServerlessDeploymentBucket"
#            - "/*"

functions:
  getTenMostRecent:
    handler: handler.getTenMostRecent
    events:
      - http:
          path: getTenMostRecent
          method: get
          cors: true

plugins:
  - serverless-python-requirements
